version: '3.8'
services:
  server:
    build: ./packages/server
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./packages/server:/app
      - /app/node_modules
    command: >
      sh -c "yarn prisma db push && yarn nest start --watch"
    depends_on:
      db:
        condition: service_healthy
  db:
    build: ./packages/db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 5
  client:
    build: ./packages/client
    working_dir: /app
    volumes:
      - ./packages/client:/app
      - /app/node_modules
    command: >
      sh -c "yarn run dev --host"
    ports:
      - "80:80"